"""Safe, account-state-preserving BlueStacks reconnaissance primitives."""

from .navigation import (
    HISTORICAL_CLIENT_VERSION,
    AdbFrameSource,
    AdbInputDriver,
    Frame,
    NavigationAgent,
    NavigationGraph,
    NavigationPolicy,
    OCRAnchor,
    SafeAction,
    SafeNavigationError,
    ScreenState,
    SessionJournal,
    StateRecognizer,
)
from .shadow_observer import (
    DEFAULT_EVIDENCE_DIR,
    DEFAULT_OUTPUT,
    AdbShadowFrameSource,
    ObservationStore,
    ShadowObserver,
    ShadowObserverConfig,
    ShadowObserverError,
    change_score,
    extract_candidate_values,
    perceptual_fingerprint,
)

__all__ = [
    "AdbFrameSource",
    "AdbInputDriver",
    "HISTORICAL_CLIENT_VERSION",
    "Frame",
    "NavigationAgent",
    "NavigationGraph",
    "NavigationPolicy",
    "OCRAnchor",
    "SafeAction",
    "SafeNavigationError",
    "ScreenState",
    "SessionJournal",
    "StateRecognizer",
    "AdbShadowFrameSource",
    "DEFAULT_EVIDENCE_DIR",
    "DEFAULT_OUTPUT",
    "ObservationStore",
    "ShadowObserver",
    "ShadowObserverConfig",
    "ShadowObserverError",
    "change_score",
    "extract_candidate_values",
    "perceptual_fingerprint",
]
